# Generated by Django 6.0.7 on 2026-07-25 20:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsnManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsncode',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
