# Generated by Django 6.0.7 on 2026-07-29 19:01

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsnManager', '0002_hsncode_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsncode',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
